INSERT INTO PAIS VALUES (1,'Brasil');
INSERT INTO UNIAO_FEDERATIVA VALUES (1,'Rio Grande do Sul','RS',1);
INSERT INTO MUNICIPIO VALUES (1,'Porto Alegre',1);
INSERT INTO BAIRRO VALUES (1,'Passo dAreia',1);
INSERT INTO ENDERECO VALUES (1,'Av. Andaraí, 531',1);